server:
  port: 18500
spring:
  application:
    name: hc-getway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: service-auth
        uri: lb://HC-AUTH
        predicates:
          - Path=/hc-auth/**
      - id: service-sys
        uri: lb://HC-SYS
        predicates:
          - Path=/hc-sys/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18000/eureka/