server:
  port: 18500
spring:
  application:
    name: hc-getway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
            routes:
              - id: lb://HC-AUTH
                uri: http://localhost:18200
                predicates:
                  - Path=/hc-auth
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18000/eureka/