server:
  port: 18300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18000/eureka/
spring:
  redis:
    host: 127.0.0.1
    database: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
    #      jdbc-url: jdbc:mysql://localhost:3306/murphy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/murphy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 666666
auth_server: http://localhost:18200
#===========认证配置==================
security:
  oauth2:
    resource:
      jwt:
        key-uri: ${auth_server}/oauth/token_key
      #获取用户认证信息
      #user-info-uri: http://localhost:10001/users/current
    #客户端配置
    client:
      #客户端ID
      client_id: murphy
      #客户端验证码
      client-secret: 123456
      #获取token的地址
      access-token-uri: ${auth_server}/oauth/token
      #认证类型
      grant-type: password
      #作用域
      scope: read,write
      user-authorization-uri: ${auth_server}/oauth/authorize
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.murphy.gee.sys.entity
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql