server:
  port: 12001
spring:
  application:
    name: MurphySys
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/murphy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#============MyBatis配置==============================
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.murphy.sys.entity


#============分页插件=======================
pagehelper:
  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql