spring:
  application:
    name: murphy-crm
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/murphy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      maximum-pool-size: 20
    url: jdbc:mysql://localhost:3306/murphy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 666666
server:
  port: 11002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/

#============MyBatis配置==============================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gee.murphy.common.entity.crm
#============分页插件=======================
pagehelper:
  helperDialect: mysql
  support-methods-arguments: true
  params: count=countSql
  reasonable: true
#============关闭Ribbon重试机制===============
ribbon:
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 4000
  ConnectTimeout: 3000
tx-lcn:
  logger:
    enabled: true
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/tx-logger?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 666666
logging:
  level:
    com:
      codingapi:
        txlcn: debug