server:
  port: 12001
spring:
  application:
    name: MurphySys
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/murphy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#============MyBatis配置==============================
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.murphy.sys.entity


#============分页插件=======================
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  
#============分布式事务===============
tm:
  manager:
    url: http://localhost:10002/tx/manager/
tx-manager:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    MaxAutoRetriesNextServer: 0
ribbon:
  eureka:
    enabled: true
  readTimeout: 6000
  ConnectTimeout: 6000